-- 코드를 입력하세요
SELECT b.USER_ID, b.NICKNAME,
CONCAT(b.CITY, ' ',b.STREET_ADDRESS1,' ',b.STREET_ADDRESS2 ) AS 전체주소, 
CONCAT(SUBSTRING(b.TLNO, 1, 3), '-', SUBSTRING(b.TLNO, 4, 4), '-', SUBSTRING(b.TLNO, 8)) AS 전화번호
FROM USED_GOODS_BOARD a 
JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
GROUP BY b.USER_ID
HAVING COUNT(a.BOARD_ID) >= 3
ORDER BY b.USER_ID DESC