-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS(
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR +1 FROM TIME_TABLE
    WHERE HOUR <23

)

SELECT t.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME_TABLE t
LEFT JOIN ANIMAL_OUTS a ON T.HOUR = HOUR(A.DATETIME)
GROUP BY t.HOUR
ORDER BY t.HOUR