SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    -- 1. 8~10월 사이 총 대여 횟수가 5회 이상인 CAR_ID 추출
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
-- 2. 메인 쿼리에서도 8~10월 데이터로 한정
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
-- 3. 추가 조건: 대여 횟수가 0인 달은 제외 (HAVING COUNT(*) > 0)
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;