-- 코드를 입력하세요
SELECT distinct b.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
WHERE a.CAR_TYPE ='세단' 
AND b.START_DATE LIKE '____-10-__'
ORDER BY CAR_ID DESC