-- 코드를 입력하세요
SELECT distinct r.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR r JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON r.CAR_ID = h.CAR_ID
WHERE CAR_TYPE = '세단'
AND MONTH(START_DATE) = 10
ORDER BY r.CAR_ID DESC